i = int(input('Digite um numero: '))
print(type(i))
print(i)
f = float(input('Digite outro numero: '))
print(type(f))
print(f)
s = input('Digite mais um numero: ')
print(type(s))
print()
b = bool(input('Digite (ou não) um numero: '))
print(type(b))
print(b)

